management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: 'always'
    beans:
      enabled: true
    info:
      enabled: true
  server:
    address: 'localhost'
    port: 11001

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false
  thymeleaf:
    cache: false
    prefix: 'classpath:/templates/'
    check-template-location: true
    suffix: .html
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'poly'
    password: '1234'
    url: 'jdbc:mariadb://localhost:3306/myDB'
  application:
    name: NOTICE-SERVICE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  token:
    creator: 'poly'
    refresh:
      valid:
        time: 3000
      name: jwtRefreshToken
    access:
      valid:
        time: 300
      name: jwtAccessToken
  secret:
    key: '2132123132313213321'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: 'http://localhost:8761/eureka'

server:
  port: '11000'
